networks:
  proxy:
    external: true
    name: proxy

services:
  mario-agent:
    build: .
    container_name: mario-agent
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy
    volumes:
      - ./auth_whatsapp:/app/auth_whatsapp
      - ./mario-agent.db:/app/mario-agent.db
      - ./config.json:/app/config.json
      - ./src:/app/src
